### ISSUE TITLE
Firmware is not valid for TMC2226-EVAL-KIT

### ISSUE THREAD

**Issue by jeremyherbert** [analogdevicesinc/TMC-EvalSystem#2]
(I also filed a case at analog devices support, CS-351781-L6J0W6. Not sure if either of these is the best place to do this but my case has not been allocated to anyone)

I purchased a TMC2226-EVAL-KIT last week from Mouser and I am trying to get it set up. When I open the TMCL-IDE it has the error "Selection is not supported! Id: 22 EVAL: TMC2226-EVAL".
 
On the page for the TMC2226-EVAL-KIT it says I need to use the latest nightly firmware here: https://github.com/trinamic/TMC-EvalSystem/releases - however, when I try to flash this firmware 3.09.5 I get the following log output:
 
 ```
Firmwareupdate started @ttyACM0/USB/id1/Landungsbruecke
Active firmware: (0012V307)
Enter bootloader mode...
Disconnecting...
Active firmware: (0012B100)
Reconnected.
Try to read bootloader version at id 1... (1)
Bootloader: 0012B100
Module (0012B100) and Firmware (0026V309) do not match!
```
 
And then the firmware update does not proceed. Can you please tell me where I can get the correct firmware for my device?

**Comment by Lionheart1810** [comment]
Hi,
with that EVAL-KIT I assume you have the Landungsbruecke V2.X or V1.X as base board?
For that, you have to flash the regular Landungsbruecke firmware hex file, not the LandungsbrueckeV3.
I just drafted a new pre-release with the recent changes and both firmware files, you can get them from there.

**Comment by jeremyherbert** [comment]
Yes, it is a V2 board. Your new release fixes the issue, thanks!
