### ISSUE TITLE
Link to AN038 in README.md does not lead to application note

### ISSUE THREAD

**Issue by fabianmuehlberger** [analogdevicesinc/TMC-EvalSystem#3]
The link: "[AN038: Using TRINAMIC’s IC Software API and Examples](https://www.trinamic.com/fileadmin/assets/Support/AppNotes/AN038_Using_TRINAMICs_IC_Software_API_and_Examples.pdf)" in the README.md page does not lead to the application note, but instead to "https://www.analog.com/en/design-center/landing-pages/001/trinamic-support.html"

On the analog.com website, this seems to be the correct link: 
https://www.analog.com/en/design-center/landing-pages/001/trinamic-support.html

**Comment by trinamic-ASU** [comment]
Thank you for your feedback. The link has been updated.
