### ISSUE TITLE
TMC2300 EVAL-KIT missing firmware

### ISSUE THREAD

**Issue by fabianmuehlberger** [analogdevicesinc/TMC-EvalSystem#4]
When running the TMC IDE, the user is prompted to lead the firmware for the TMC2300 EVAL board. 
The link leads to the analog landing page, but there is no driver to be found on the product specific website. 

* Landungsbruecke v2.0
* TMC2300-EVAL v1.1
* TMC_IDE v3.9
* current firmware [v 3.07]

![firmware_update](https://github.com/trinamic/TMC-EvalSystem/assets/56475821/b38b7a8f-f2ce-4f46-9596-bf1c31a0b4f0)

It is unclear to me if it is a problem with the EVAL system, or with the analog.com website having some problems with links all leading to the landing page

**Comment by fabianmuehlberger** [comment]
The issue is resolved with the help of support. 

The problem I see is, that the TMC_IDE links to the analog.com website, where a direct link to the release should be. This would be less confusing.

**Comment by trinamic-ed** [comment]
Hello Fabian,

thanks for let us know the issue with the link. It will be fixed in the TMCL-IDE. It is a leftover from the movement of our website from trinamic.com to analog.com that happened ~2 weeks ago.

Regards,
      Enrico
