### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fabianmuehlberger** [analogdevicesinc/TMC-EvalSystem#5]
HI, 
I planned to hook up the TMC2300-BOB directly to the Landungsbrücke, but noticed, that there no documentation for the EVAL system on the analog.com website, beside the link to the IDE.  

From what is available, it is not clear how to do this correctly, and if it is even possible. 
The reason I am looking into this option is to program and inspect a custom driver board withing the TMC IDE. 

The things I am most interested in are:
* How to set it up correctly
* what pins on the EVAL board or the Eselsbrücke are the RX and TX pins as well as the needed EN, VIO etc.

**Comment by contrebande-labs** [comment]
I'm on Ubuntu 22.04 and  this is what I needed to do to build the firmware:
* install the toolchain: `sudo apt install gcc-arm-none-eabi`
* specify the target architecture: `export DEVICE=Landungsbruecke`
* build the firmware with `make` 
* uploaded the `Landungsbruecke_v3.09.6_BL.hex` in the build folder `_build_Landungsbruecke` using the TMCL-IDE

And everything works fine for me. I can run my scrips in the TMCL/Pc host. I therefore think you can send TMCL commands to the board using the serial port or even to burn some scripts into the `main.c` program...

I agree that some documentation would indeed be welcome, however.

**Comment by fabianmuehlberger** [comment]
Hi,  
Do I understand correctly: You are using the Landungsbruecke with the TMCL IDE to interact with a breakout board? 
Ideally, I would tune and program my custom tmc2300 driver boards, but was not sure if that is possible (my tmc2300 eval board has an EEPROM and I assumed that it stores the board information).

Can you explain in more detail?

I have not used the tool chain so far, but will look into it. My use case, will be an implementation for esp-idf/esphome and therefore utilizing the API.

Regarding the documentation: I just proposed to create a documentation for the TMC-API using readthedocs, and it would make sense for the eval system too.

**Comment by trinamic-ed** [comment]
Hello,

the typical way to try out one of our eval boards is to connect it with the Landungsbrücke (as shown in the pictures here: [landungsbrucke-eval-system.html](https://www.analog.com/en/design-center/evaluation-hardware-and-software/motor-motion-control-software/landungsbrucke-eval-system.html)) and connect the Landungsbrücke via USB with your PC/Laptop. 

The EEPROMs on the eval boards contain some information for the Landungsbrücke. This helps to automatically check the connected eval boards on power up and load/map the right software part. It is also used for the TMCL-IDE to select the right motion / driver eval board automatically.

If you use a Landungsbrücke you can also connect and communicate with the eval board to set/read registers via Python (using our [PyTrinamic ](https://pypi.org/project/pytrinamic/) package. There is an example folder with small examples for the most of our boards.

Regards,
     Enrico
