### ISSUE TITLE
Undocumented Register in TMC4671_eval.c - 0x5F

### ISSUE THREAD

**Issue by ZedOud** [analogdevicesinc/TMC-EvalSystem#8]
TMC4671_eval.c starting from line 220 uses the register `TMC4671_PID_ACCELERATION_LIMIT` which is at address 0x5F.

However, the TMC4671 data sheet does not describe the register at 0x5F or any register named `PID_ACCELERATION_LIMIT` in its list of registers.

https://www.analog.com/media/en/technical-documentation/data-sheets/TMC4671.pdf

The listed registers skips from 0x5E to 0x60.

**Comment by trinamic-ASU** [comment]
Thanks for pointing this out. We have removed this register and corresponding mask and shift definitions from the whole project.
