### ISSUE TITLE
Incompatible bootloader error (Startrampe support)

### ISSUE THREAD

**Issue by imwhocodes** [analogdevicesinc/TMC-EvalSystem#9]
Hi
I bought a new _**TMC2160-EVAL**_ that I wanted to pair with an old _**Startrampe**_ I had lay around in the lab

In particular the system is composed of:
1. Startrampe **v0.4**
2. Eselsbruecke **v1.2**
3. TMC2160-EVAL **v1.1**

The board was not recognising the TMC2160 daughter board and the link "download firmware from Trinamic" was bringing me simply to the [development suite intro webpage](https://www.analog.com/en/resources/evaluation-hardware-and-software/motor-motion-control-software/landungsbrucke-eval-system.html)

So I tried to upload/flash the firmware from the [latest release from this repo](https://github.com/analogdevicesinc/TMC-EvalSystem/releases/tag/3.10.2) but I get the error:

```
Firmwareupdate started @COM4/USB/id1/Startrampe
Active firmware: (0011B102)
Try to read bootloader version at id 1... (1)
Bootloader: 0011B102
Module (0011B102) and Firmware (0026V310) do not match!
```
<img width="783" alt="Screenshot 2024-06-17 at 13 41 53" src="https://github.com/analogdevicesinc/TMC-EvalSystem/assets/14922653/7637dde0-0c23-4d1b-8c4d-e1d78d01ba13">

Do I also need the updated booloader?
Is the firmware compatible?

Thanks,
Luca

**Comment by imwhocodes** [comment]
I was able to obtain the firmware by myself,
If anybody else need it this is the procedure:

```
git clone --recurse-submodules https://github.com/analogdevicesinc/TMC-EvalSystem.git
cd TMC-EvalSystem
git checkout 3.08.24
git clone https://github.com/analogdevicesinc/TMC-API.git
cd TMC-API
git checkout 5b3c019da5d278df57db580781ee771accc70371
cd ..
export DEVICE=Startrampe
make
```

After compilation the firmware will be located at `./_build_Startrampe/Startrampe_v3.08.24_BL.hex`

On MacOs if you don't have the correct compiler (`arm-none-eabi-gcc`) you can install it with `brew install --cask gcc-arm-embedded`

I would like to attach the firmware file itself here but it seem like it was removed from this repo because of some licensing problems, so I'm only putting the instructions for it

**Comment by trinamic-LH** [comment]
Hello @imwhocodes ,
the Startrampe was indeed removed and is no longer officially supported. It has long been superseeded by the Landungsbruecke, and, as you already noted, the source code had a licensing issue (hence it being removedfrom current code).
